import { FormEvent, useState } from 'react';
import { Conversation, Message, UserProfile } from '../../types';
import { Button } from '../ui/Button';

export function ChatPanel({ user, conversations, messages, activeId, onSelect, onSend, onToggleEmail }: { user: UserProfile; conversations: Conversation[]; messages: Message[]; activeId?: string; onSelect: (id: string) => void; onSend: (conversationId: string, body: string) => void; onToggleEmail: (conversationId: string) => void; }) {
  const active = conversations.find((c) => c.id === activeId) ?? conversations[0];
  const [body, setBody] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); if (active && body.trim()) { onSend(active.id, body.trim()); setBody(''); } };
  if (!active) return <div className="card p-8 text-center text-slate-500">Noch keine Gespräche. Kontaktiere eine Anbieterin über eine Produktdetailseite.</div>;
  const activeMessages = messages.filter((m) => m.conversationId === active.id);
  return <div className="grid gap-4 lg:grid-cols-[320px_1fr]"><aside className="card divide-y divide-slate-100 overflow-hidden">{conversations.map((conversation) => <button key={conversation.id} onClick={() => onSelect(conversation.id)} className={`block w-full p-4 text-left ${conversation.id === active.id ? 'bg-sage/10' : 'hover:bg-slate-50'}`}><b className="text-ocean">{conversation.listingName}</b><p className="text-xs text-slate-500">Zuletzt: {new Date(conversation.updatedAt).toLocaleString('de-DE')}</p></button>)}</aside><section className="card flex min-h-[560px] flex-col p-5"><div className="mb-4 flex items-start justify-between gap-4 border-b border-slate-100 pb-4"><div><h3 className="text-xl font-bold text-ocean">{active.listingName}</h3><p className="text-sm text-slate-500">Lokaler Chat-Prototyp ohne echte E-Mail.</p></div><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={active.emailNotifications[user.id] ?? false} onChange={() => onToggleEmail(active.id)} className="accent-sage"/> E-Mail-Benachrichtigung bei neuen Nachrichten</label></div><div className="flex-1 space-y-3 overflow-y-auto">{activeMessages.map((message) => <div key={message.id} className={`max-w-[80%] rounded-3xl px-4 py-3 text-sm ${message.senderId === user.id ? 'ml-auto bg-sage text-white' : 'bg-slate-100 text-slate-700'}`}><p>{message.body}</p><small className="mt-1 block opacity-70">{new Date(message.createdAt).toLocaleString('de-DE')}</small></div>)}</div><form onSubmit={submit} className="mt-4 flex gap-2"><input className="input" value={body} onChange={(e) => setBody(e.target.value)} placeholder="Nachricht schreiben..."/><Button>Senden</Button></form></section></div>;
}
