import { FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { categories } from '../data/mockListings';
import { Listing, UserProfile } from '../types';
import { Button } from '../components/ui/Button';

export function ListingForm({ user, onSave, initial }: { user: UserProfile; onSave: (listing: Listing) => void; initial?: Listing }) {
  const navigate = useNavigate();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const status = String(data.get('status')) as Listing['status']; const listing: Listing = { id: initial?.id ?? `l-${Date.now()}`, name: String(data.get('name')), category: String(data.get('category')) as Listing['category'], description: String(data.get('description')), ingredients: String(data.get('ingredients') || ''), quantity: String(data.get('quantity') || ''), zipCode: String(data.get('zipCode') || user.zipCode), city: String(data.get('city')), images: [String(data.get('image') || 'https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?auto=format&fit=crop&w=900&q=80')], createdAt: initial?.createdAt ?? new Date().toISOString(), status, ownerId: user.id, ownerName: user.firstName, ownerProfileVisible: user.aboutVisibility === 'public', allergens: String(data.get('allergens') || ''), shelfLife: String(data.get('shelfLife') || ''), storageNotes: String(data.get('storageNotes') || ''), productionDate: String(data.get('productionDate') || ''), availability: String(data.get('availability') || ''), popularity: initial?.popularity ?? 0 }; onSave(listing); navigate('/member?tab=listings'); };
  return <form onSubmit={submit} className="card space-y-6 p-8"><h1 className="text-3xl font-black text-ocean">{initial ? 'Anzeige bearbeiten' : 'Anzeige erstellen'}</h1><p className="text-slate-600">Pflichtfelder sind markiert. Keine Preise, Reservierungen oder Versand-/Abhollogik im MVP.</p><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="label">Name des Produkts *</span><input name="name" className="input" required defaultValue={initial?.name}/></label><label className="space-y-2"><span className="label">Ort *</span><input name="city" className="input" required defaultValue={initial?.city ?? user.city}/></label><label className="space-y-2"><span className="label">Kategorie</span><select name="category" className="input" defaultValue={initial?.category ?? 'Backwaren'}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="space-y-2"><span className="label">PLZ</span><input name="zipCode" className="input" defaultValue={initial?.zipCode ?? user.zipCode}/></label><label className="space-y-2 md:col-span-2"><span className="label">Beschreibung *</span><textarea name="description" className="input min-h-28" required defaultValue={initial?.description}/></label><label className="space-y-2"><span className="label">Zutaten</span><input name="ingredients" className="input" defaultValue={initial?.ingredients}/></label><label className="space-y-2"><span className="label">Menge</span><input name="quantity" className="input" defaultValue={initial?.quantity}/></label><label className="space-y-2"><span className="label">Bild URL</span><input name="image" className="input" defaultValue={initial?.images[0]}/></label><label className="space-y-2"><span className="label">Allergene</span><input name="allergens" className="input" defaultValue={initial?.allergens}/></label><label className="space-y-2"><span className="label">Herstellungsdatum</span><input name="productionDate" type="date" className="input" defaultValue={initial?.productionDate}/></label><label className="space-y-2"><span className="label">Haltbarkeit</span><input name="shelfLife" className="input" defaultValue={initial?.shelfLife}/></label><label className="space-y-2"><span className="label">Verfügbarkeit</span><input name="availability" className="input" defaultValue={initial?.availability}/></label><label className="space-y-2"><span className="label">Hinweise zur Lagerung</span><input name="storageNotes" className="input" defaultValue={initial?.storageNotes}/></label><label className="space-y-2"><span className="label">Status</span><select name="status" className="input" defaultValue={initial?.status ?? 'active'}><option value="draft">Entwurf</option><option value="active">aktiv</option><option value="paused">pausiert</option><option value="deleted">gelöscht</option></select></label></div><Button>{initial ? 'Änderungen speichern' : 'Anzeige speichern'}</Button></form>;
}
export function CreateListingPage({ user, onSave }: { user?: UserProfile; onSave: (listing: Listing) => void }) { if (!user) return <div className="container-page py-12"><div className="card p-8">Bitte einloggen, um eine Anzeige zu erstellen.</div></div>; return <div className="container-page max-w-5xl py-12"><ListingForm user={user} onSave={onSave}/></div>; }
