import { Link } from 'react-router-dom';
import { Listing, Conversation, UserProfile } from '../types';
import { ListingCard } from '../components/listings/ListingCard';

export function HomePage({ user, listings, conversations }: { user?: UserProfile; listings: Listing[]; conversations: Conversation[] }) {
  const nearby = listings.filter((l) => l.status === 'active').slice(0, 3);
  const ownActive = user ? listings.filter((l) => l.ownerId === user.id && l.status === 'active') : [];
  if (user) return <div className="container-page py-10"><section className="card grid gap-8 p-8 md:grid-cols-[1.2fr_.8fr]"><div><span className="badge bg-coral/15 text-coral">Willkommen zurück, {user.firstName}</span><h1 className="mt-4 text-4xl font-black tracking-tight text-ocean md:text-5xl">Was möchtest du heute regional teilen oder entdecken?</h1><p className="mt-4 text-lg text-slate-600">Dein persönlicher Überblick über Produkte in deiner Nähe, letzte Nachrichten und eigene aktive Anzeigen.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" to="/listings/new">Anzeige erstellen</Link><Link className="btn-secondary" to="/search">Produkte finden</Link></div></div><div className="rounded-3xl bg-sage/10 p-6"><h2 className="font-bold text-ocean">Kurzübersicht</h2><p className="mt-3 text-sm text-slate-600">{nearby.length} Produkte aus deiner Nähe</p><p className="text-sm text-slate-600">{conversations.length} letzte Nachrichtenverläufe</p><p className="text-sm text-slate-600">{ownActive.length} eigene aktive Anzeigen</p></div></section><h2 className="mt-10 text-2xl font-bold text-ocean">Produkte aus deiner Nähe</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{nearby.map((listing) => <ListingCard key={listing.id} listing={listing}/>)}</div></div>;
  return <div className="container-page py-10"><section className="grid items-center gap-8 py-8 lg:grid-cols-[1.2fr_.8fr]"><div><span className="badge bg-sage/15 text-ocean">Regional · selbstgemacht · persönlich</span><h1 className="mt-5 text-4xl font-black tracking-tight text-ocean md:text-6xl">Selbstgemachte Produkte von Menschen für Menschen aus deiner Nähe</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Entdecke handgemachte Food-Produkte privater Anbieterinnen und Anbieter. Kein Warenkorb, keine Bezahlung – im MVP endet alles bewusst mit direkter Kontaktaufnahme.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" to="/register">Konto erstellen</Link><Link className="btn-ghost" to="/search">Produkte finden</Link></div></div><div className="card p-5"><img className="h-72 w-full rounded-3xl object-cover" src="https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=900&q=80" alt="Regionale Lebensmittel"/></div></section><div className="grid gap-5 md:grid-cols-3">{['Regionale Anbieter entdecken','Selbstgemachte Produkte finden','Direkt Kontakt aufnehmen'].map((title, index) => <div key={title} className="card p-6"><div className="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-sage/15 font-black text-ocean">{index + 1}</div><h2 className="text-xl font-bold text-ocean">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">Ein klarer, reduzierter Flow für lokale Food-Angebote ohne Transaktionslogik.</p></div>)}</div></div>;
}
