import { FormEvent, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { UserProfile } from '../types';
import { Button } from '../components/ui/Button';

export function RegisterPage({ onRegister }: { onRegister: (user: UserProfile) => void }) {
  const navigate = useNavigate();
  const [intent, setIntent] = useState<'offer' | 'explore'>('offer');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const user: UserProfile = { id: `u-${Date.now()}`, role: 'member', email: String(data.get('email')), firstName: String(data.get('firstName')), lastName: String(data.get('lastName') || ''), zipCode: String(data.get('zipCode')), city: String(data.get('city') || ''), avatarUrl: String(data.get('avatarUrl') || ''), phone: String(data.get('phone') || ''), about: String(data.get('about') || ''), aboutVisibility: String(data.get('aboutVisibility')) as 'public' | 'private', emailVerified: false, phoneVerified: false, profileComplete: false, ratingAverage: 0, ratingCount: 0 }; onRegister(user); navigate(intent === 'offer' ? '/listings/new' : '/search'); };
  return <div className="container-page max-w-4xl py-12"><form onSubmit={submit} className="card space-y-6 p-8"><h1 className="text-3xl font-black text-ocean">Konto erstellen</h1><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="label">E-Mail *</span><input name="email" className="input" required type="email"/></label><label className="space-y-2"><span className="label">Passwort *</span><input name="password" className="input" required type="password" minLength={6}/></label><label className="space-y-2"><span className="label">Vorname *</span><input name="firstName" className="input" required/></label><label className="space-y-2"><span className="label">Nachname (optional)</span><input name="lastName" className="input"/></label><label className="space-y-2"><span className="label">PLZ *</span><input name="zipCode" className="input" required/></label><label className="space-y-2"><span className="label">Ort (optional)</span><input name="city" className="input"/></label><label className="space-y-2"><span className="label">Profilbild URL (optional)</span><input name="avatarUrl" className="input"/></label><label className="space-y-2"><span className="label">Telefonnummer (optional)</span><input name="phone" className="input"/></label></div><label className="space-y-2 block"><span className="label">Über mich (optional)</span><textarea name="about" className="input min-h-28"/></label><div><span className="label">Sichtbarkeit von „Über mich“</span><div className="mt-2 flex gap-4"><label><input type="radio" name="aboutVisibility" value="public" defaultChecked className="accent-sage"/> öffentlich</label><label><input type="radio" name="aboutVisibility" value="private" className="accent-sage"/> privat</label></div></div><div className="rounded-3xl bg-cream p-5"><p className="font-bold text-ocean">Was möchtest du zuerst tun?</p><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="rounded-2xl border bg-white p-4"><input type="radio" checked={intent === 'offer'} onChange={() => setIntent('offer')} className="accent-sage"/> Ich möchte etwas anbieten</label><label className="rounded-2xl border bg-white p-4"><input type="radio" checked={intent === 'explore'} onChange={() => setIntent('explore')} className="accent-sage"/> Ich möchte regionale Anbieter erkunden</label></div></div><Button>Konto erstellen</Button></form></div>;
}
